=== Reddmist/QTestLibPlugin/qtestliboutput.dtd
<!DOCTYPE qtestliboutput [
    <!ELEMENT qtestliboutput (results,root|class)>
    <!ELEMENT root (class+)>
    <!ELEMENT class (function+)>
    <!ELEMENT function (row+|message+)>
    <!ELEMENT row (message+)>
    <!ELEMENT message (#PCDATA)>
    <!ELEMENT results (unsure*,magicfound+|magicnotfound+,unsure*)>
    <!ELEMENT unsure EMPTY>
    <!ELEMENT magicfound EMPTY>
    <!ELEMENT magicnotfound EMPTY>

    <!ATTLIST root type CDATA "Unknown">

    <!ATTLIST class name CDATA #REQUIRED>
    <!ATTLIST class type CDATA "Unknown">

    <!ATTLIST function name CDATA #REQUIRED>
    <!ATTLIST function type CDATA "Unknown">

    <!ATTLIST row title CDATA #REQUIRED>
    <!ATTLIST row type CDATA "Unknown">

    <!ATTLIST message type CDATA "Unknown">
    <!ATTLIST message strict>
]>

=== Reddmist/QTestLibPlugin/tests/OneSubTest/onesubtest.xml
<?xml version="1.0" ?>
<!DOCTYPE qtestliboutput SYSTEM "../../qtestliboutput.dtd">
<qtestliboutput>
    <results format="xunitxml">
        <unsure level="silent" />
        <unsure level="silent" />
        <unsure level="silent" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure level="silent" />
    </results>
    <results format="lightxml">
        <unsure level="silent" />
        <unsure level="silent" />
        <unsure level="silent" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="silent" />
    </results>
    <results format="xml">
        <unsure level="silent" />
        <unsure level="silent" />
        <unsure level="silent" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="silent" />
    </results>
    <results format="txt">
        <unsure level="silent" />
        <unsure level="silent" />
        <unsure level="silent" />
        <unsure/>
        <magicfound level="silent" />
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="silent" />
        <unsure/>
        <unsure level="silent" />
    </results>
    <class name="OnePassTest" type="Pass" format="!lightxml" level="normal">
        <function name="initTestCase" type="Pass">
            <message type="Info" strict="true" level="verbose1" format="txt">
                entering
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false" format="xml" >
                0.00ms
            </message>
        </function>
        <function name="testPass" type="Pass">
            <message type="Info" strict="true" level="verbose1" format="txt">
                entering
            </message>
            <message type="Info" strict="true" level="verbose2" file="onepasstest.cpp" line="34">
                QVERIFY(true)
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false" format="xml" >
                0.00ms
            </message>
        </function>
        <function name="cleanupTestCase" type="Pass">
            <message type="Info" strict="true" level="verbose1" format="txt">
                entering
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false" format="xml" >
                0.00ms
            </message>
        </function>
        <message type="Duration" strict="false" format="xml" >
            0.00ms
        </message>
    </class>
    <class name="OneSubTest" type="Pass" format="lightxml" level="normal">
        <function name="initTestCase" type="Pass">
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false">
                0.00ms
            </message>
        </function>
        <function name="testPass" type="Pass">
            <message type="Info" strict="true" level="verbose2" file="onepasstest.cpp" line="34">
                QVERIFY(true)
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false">
                0.00ms
            </message>
        </function>
        <function name="cleanupTestCase" type="Pass">
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false">
                0.00ms
            </message>
        </function>
        <message type="Duration" strict="false">
            0.00ms
        </message>
    </class>
</qtestliboutput>

=== Reddmist/QTestLibPlugin/tests/MakefileSpaceTest/makefilespacetest.xml
<?xml version="1.0" ?>
<!DOCTYPE qtestliboutput SYSTEM "../../qtestliboutput.dtd">
<qtestliboutput>
    <results format="xunitxml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
    </results>
    <results format="lightxml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
    </results>
    <results format="xml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
    </results>
    <results format="txt">
        <unsure/>
        <magicfound level="silent" />
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="silent" />
        <unsure/>
    </results>
    <class name="OnePassTest" type="Pass" format="!lightxml" level="normal">
        <function name="initTestCase" type="Pass">
            <message type="Info" strict="true" level="verbose1" format="txt">
                entering
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false" format="xml" >
                0.00ms
            </message>
        </function>
        <function name="testPass" type="Pass">
            <message type="Info" strict="true" level="verbose1" format="txt">
                entering
            </message>
            <message type="Info" strict="true" level="verbose2" file="onepasstest.cpp" line="34">
                QVERIFY(true)
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false" format="xml" >
                0.00ms
            </message>
        </function>
        <function name="cleanupTestCase" type="Pass">
            <message type="Info" strict="true" level="verbose1" format="txt">
                entering
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false" format="xml" >
                0.00ms
            </message>
        </function>
        <message type="Duration" strict="false" format="xml" >
            0.00ms
        </message>
    </class>
    <class name="OneSubTest" type="Pass" format="lightxml" level="normal">
        <function name="initTestCase" type="Pass">
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false">
                0.00ms
            </message>
        </function>
        <function name="testPass" type="Pass">
            <message type="Info" strict="true" level="verbose2" file="onepasstest.cpp" line="34">
                QVERIFY(true)
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false">
                0.00ms
            </message>
        </function>
        <function name="cleanupTestCase" type="Pass">
            <message type="Pass" strict="true">
                Test passed
            </message>
            <message type="Duration" strict="false">
                0.00ms
            </message>
        </function>
        <message type="Duration" strict="false">
            0.00ms
        </message>
    </class>
</qtestliboutput>

=== Reddmist/QTestLibPlugin/tests/TwoSubTests/twosubtests.xml
<?xml version="1.0" ?>
<!DOCTYPE qtestliboutput SYSTEM "../../qtestliboutput.dtd">
<qtestliboutput>
    <results format="xunitxml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
    </results>
    <results format="lightxml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
    </results>
    <results format="xml">
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <magicfound />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
        <unsure />
    </results>
    <results format="txt">
        <unsure/>
        <magicfound level="silent" />
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="silent" />
        <unsure/>
        <unsure/>
        <magicfound level="silent" />
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure level="verbose2" />
        <unsure level="verbose2" />
        <unsure level="silent" />
        <unsure level="silent" />
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="silent" />
        <unsure/>
    </results>
    <root type="Fail">
        <class name="OnePassTest" type="Pass" format="!lightxml">
            <function name="initTestCase" type="Pass">
                <message type="Info" strict="true" level="verbose1" format="txt">
                    entering
                </message>
                <message type="Pass" strict="true">
                    Test passed
                </message>
                <message type="Duration" strict="false" format="xml">
                    0ms
                </message>
            </function>
            <function name="testPass" type="Pass">
                <message type="Info" strict="true" level="verbose1" format="txt">
                    entering
                </message>
                <message type="Info" strict="true" level="verbose2" file="onepasstest.cpp" line="34">
                    QVERIFY(true)
                </message>
                <message type="Pass" strict="true">
                    Test passed
                </message>
                <message type="Duration" strict="false" format="xml">
                    0ms
                </message>
            </function>
            <function name="cleanupTestCase" type="Pass">
                <message type="Info" strict="true" level="verbose1" format="txt">
                    entering
                </message>
                <message type="Pass" strict="true">
                    Test passed
                </message>
                <message type="Duration" strict="false" format="xml">
                    0ms
                </message>
            </function>
            <message type="Duration" strict="false" format="xml">
                0ms
            </message>
        </class>
        <class name="TwoSubTests#1" type="Pass" format="lightxml">
            <function name="initTestCase" type="Pass">
                <message type="Pass" strict="true">
                    Test passed
                </message>
                <message type="Duration" strict="false">
                    0ms
                </message>
            </function>
            <function name="testPass" type="Pass">
                <message type="Info" strict="true" level="verbose2" file="onepasstest.cpp" line="34">
                    QVERIFY(true)
                </message>
                <message type="Pass" strict="true">
                    Test passed
                </message>
                <message type="Duration" strict="false">
                    0ms
                </message>
            </function>
            <function name="cleanupTestCase" type="Pass">
                <message type="Pass" strict="true">
                    Test passed
                </message>
                <message type="Duration" strict="false">
                    0ms
                </message>
            </function>
            <message type="Duration" strict="false">
                0ms
            </message>
        </class>
        <class name="OneFailTest" type="Fail" format="!lightxml">
            <function name="initTestCase" type="Pass">
                <message type="Info" strict="true" level="verbose1" format="txt">
                    entering
                </message>
                <message type="Pass" strict="true">
                    Test passed
                </message>
                <message type="Duration" strict="false" format="xml">
                    0ms
                </message>
            </function>
            <function name="testFail" type="Fail">
                <message type="Info" strict="true" level="verbose1" format="txt">
                    entering
                </message>
                <message type="Info" strict="true" level="verbose2" file="onefailtest.cpp" line="34">
                    QVERIFY(false)
                </message>
                <message type="Fail" strict="true" level="silent" file="onefailtest.cpp" line="34">
                    'false' returned FALSE. ()
                </message>
                <message type="Duration" strict="false" format="xml">
                    0ms
                </message>
            </function>
            <function name="cleanupTestCase" type="Pass">
                <message type="Info" strict="true" level="verbose1" format="txt">
                    entering
                </message>
                <message type="Pass" strict="true">
                    Test passed
                </message>
                <message type="Duration" strict="false" format="xml">
                    0ms
                </message>
            </function>
            <message type="Duration" strict="false" format="xml">
                0ms
            </message>
        </class>
        <class name="TwoSubTests#2" type="Fail" format="lightxml">
            <function name="initTestCase" type="Pass">
                <message type="Pass" strict="true">
                    Test passed
                </message>
                <message type="Duration" strict="false">
                    0ms
                </message>
            </function>
            <function name="testFail" type="Fail">
                <message type="Info" strict="true" level="verbose2" file="onefailtest.cpp" line="34">
                    QVERIFY(false)
                </message>
                <message type="Fail" strict="true" level="silent" file="onefailtest.cpp" line="34">
                    'false' returned FALSE. ()
                </message>
                <message type="Duration" strict="false">
                    0ms
                </message>
            </function>
            <function name="cleanupTestCase" type="Pass">
                <message type="Pass" strict="true">
                    Test passed
                </message>
                <message type="Duration" strict="false">
                    0ms
                </message>
            </function>
            <message type="Duration" strict="false">
                0ms
            </message>
        </class>
    </root>
</qtestliboutput>

=== Reddmist/QTestLibPlugin/tests/SignalsTest/signalstest.xml
<?xml version="1.0" ?>
<!DOCTYPE qtestliboutput SYSTEM "qtestliboutput.dtd">
<qtestliboutput>
    <results>
        <unsure/>
        <magicfound level="silent" />
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure level="verboses" />
        <unsure level="verboses" />
        <unsure level="verboses" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure level="verboses" />
        <unsure level="verboses" />
        <unsure level="verboses" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure level="verboses" />
        <unsure level="verboses" />
        <unsure level="verboses" />
        <unsure/>
        <unsure level="verbose1" />
        <unsure/>
        <unsure level="silent" />
        <unsure/>
    </results>
    <class name="SignalsTest" type="Pass" level="normal">
        <function name="initTestCase" type="Pass">
            <message type="Info" strict="true" level="verbose1">
                entering
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
        </function>
        <function name="firstFunction" type="Pass">
            <message type="Info" strict="true" level="verbose1">
                entering
            </message>
            <message type="Info" strict="false" level="verboses">
                Signal: SignalsTest(7ffe244a1c30) signal1 ()
            </message>
            <message type="Info" strict="false" level="verboses">
                Signal: SignalsTest(7ffe244a1c30) signal2 (QString(firstFunction))
            </message>
            <message type="Info" strict="false" level="verboses">
                Signal: SignalsTest(7ffe244a1c30) signal3 (int(18), int(36))
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
        </function>
        <function name="secondFunction" type="Pass">
            <message type="Info" strict="true" level="verbose1">
                entering
            </message>
            <message type="Info" strict="false" level="verboses">
                Signal: SignalsTest(7ffe244a1c30) signal2 (QString(secondFunction))
            </message>
            <message type="Info" strict="false" level="verboses">
                Signal: SignalsTest(7ffe244a1c30) signal3 (int(54), int(72))
            </message>
            <message type="Info" strict="false" level="verboses">
                Signal: SignalsTest(7ffe244a1c30) signal1 ()
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
        </function>
        <function name="thirdFunction" type="Pass">
            <message type="Info" strict="true" level="verbose1">
                entering
            </message>
            <message type="Info" strict="false" level="verboses">
                Signal: SignalsTest(7ffe244a1c30) signal3 (int(90), int(108))
            </message>
            <message type="Info" strict="false" level="verboses">
                Signal: SignalsTest(7ffe244a1c30) signal1 ()
            </message>
            <message type="Info" strict="false" level="verboses">
                Signal: SignalsTest(7ffe244a1c30) signal2 (QString(thirdFunction))
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
        </function>
        <function name="cleanupTestCase" type="Pass">
            <message type="Info" strict="true" level="verbose1">
                entering
            </message>
            <message type="Pass" strict="true">
                Test passed
            </message>
        </function>
    </class>
</qtestliboutput>
